name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup-python-dependencies
        with:
          python-version: "3.10"
          requirements-file: "starter/backend/requirements.txt"
      
      - name: Run linter
        run: flake8 --config starter/backend/.flake8 starter/backend

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup-python-dependencies
        with:
          python-version: "3.10"
          requirements-file: "starter/backend/requirements.txt"

      - name: Run tests
        run: pytest starter/backend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker container
        run: docker run -d --name trungnq72-backend-container -p 8081:8081 trungnq72-backend-app:ci-build

      - name: Add PR Comment
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const context = github.context;
            const pullRequestNumber = context.payload.pull_request.number;
            const comment = 'BE - The build was successful!';
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: pullRequestNumber,
              body: comment,
            });
