name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r starter/backend/requirements.txt
      
      - name: Run linter
        run: flake8 --config starter/backend/.flake8 starter/backend

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r starter/backend/requirements.txt

      - name: Run tests
        run: pytest starter/backend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r starter/backend/requirements.txt

      - name: Package backend
        run: python setup.py sdist bdist_wheel
        working-directory: starter/backend

      - name: Build Docker image
        run: docker build -t trungnq72-backend-app:ci-build starter/backend
