name: Frontend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js and Install Dependencies
      uses: ./.github/actions/setup-node-dependencies
      with:
        node-version: '18'
        working-directory: starter/frontend

    - name: Run linter
      run: npm run lint
      working-directory: starter/frontend

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js and Install Dependencies
      uses: ./.github/actions/setup-node-dependencies
      with:
        node-version: '18'
        working-directory: starter/frontend

    - name: Run tests
      run: npm test
      working-directory: starter/frontend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js and Install Dependencies
      uses: ./.github/actions/setup-node-dependencies
      with:
        node-version: '18'
        working-directory: starter/frontend

    - name: Build frontend
      run: npm run build
      working-directory: starter/frontend

    - name: Build Docker image
      run: docker build -t trungnq72-frontend-app:ci-build starter/frontend

    - name: Run Docker container
      run: docker run -d --name trungnq72-frontend-container -e REACT_APP_MOVIE_API_URL=http://localhost:8081 -p 8082:8082 trungnq72-frontend-app:ci-build

    - name: Post test results as PR comment
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'FE - The build was successful!'
          });
        github-token: ${{ secrets.GITHUB_TOKEN }}